name: Push-to-EC2

# Trigger only for push to master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to EC2 when push happens to master branch
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Setup
        env:
          DBUSER: ${{ secrets.DBUSER }}
          DBHOST: ${{ secrets.DBHOST }}
          DBPW: ${{ secrets.DBPW }}
        run: |
          cd /home/${{ secrets.USERNAME }}/PlaylistAccess
          ls -l /home/${{ secrets.USERNAME }}/PlaylistAccess
          python3 -m pip install -r ./requirements.txt
          screen -S app -X quit
          screen -dmS app python3 ./src/application.py

      - name: Deploy to instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DIRECTORY }}
          

      


