name: Push-to-EC2

# Trigger only for push to master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to EC2 when push happens to master branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      
      - name: Deploy to instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DIRECTORY }}
      
      - name: Setup app
        working-directory: ${{ secrets.DIRECTORY }}
        env:
          DBUSER: ${{ secrets.DBUSER }}
          DBHOST: ${{ secrets.DBHOST }}
          DBPW: ${{ secrets.DBPW }}
        run: |
          python3 -m pip install -r requirements.txt
          screen -S app -X quit
          screen -dmS app python3 src/application.py


